* Matlab在机器学习中的应用
** 写作中问题
1. 模型、术语、MATLAB名词是否保留英文？
   - 我在翻译过程中对这些名词没有翻译，比如 k-means、k-medoids；
     MATLAB术语如 cell structure array 等。
   - 对于我认为数据分析人员必须熟知的英文模型、术语，没有翻译
   - 原因：
     - 由于MATLAB语法本身十分贴近数学公式，许多看似英文词汇的单词
       甚至直接是MATLAB语法中的关键字（kmedoids是一种聚类方法，同
       时也是MATLAB中的函数名），翻译这些关键字会对编程造成极大困
       扰
     - 方便读者学习MATLAB、阅读MATLAB帮助：MATLAB Help文档非常优
       秀，原版书中的词汇与帮助文档是一致的，如果把这些词汇翻译成
       中文，会影响读者阅读帮助文档，不利于读者学习MATLAB
     - 为了精确：我查了这些名词的中文翻译，觉得比起直接用英文更加
       晦涩、而且不准确，不如直接保留英文（例如logistic
       regression翻译成逻辑斯体克回归、linear envelope energy
       potentials翻译成线性包络能量势能函数等）
     - 方便读者从阅读翻译文献向阅读英文原文文献过渡：机器学习领域
       是新兴领域、发展速度非常快。最新、最权威的资料一定是先由英
       文写作发表的。如果想在这个领域有所成就，一定要养成阅读英文
       文献的习惯。翻译过程中对模型、术语等名词进行保留，能够加速
       读者的过渡过程，降低阅读英文文献的难度

** 目录部分
1. 前言
2. 第一章：MATLAB机器学习初步
   - 机器学习基础简介
   - 机器学习类别简介
     - 监督学习
     - 非监督学习
     - 强化学习
   - 选择正确的算法
   - 手把手构建机器学习模型
   - 简介MATLAB中的机器学习工具
     - 系统与平台要求
     - 配置MATLAB
   - 统计与机器学习工具箱
     - 数据类型
       - 支持的数据类型
       - 不支持的数据类型
     - 工具箱功能简介
       - 数据挖掘及可视化
       - 回归分析
       - 分类
       - 聚类分析
       - 降维
   - 神经网络工具箱
   - MATLAB中的统计学和线性代数
   - 总结
3. 第二章：MATLAB中的数据处理
   + 熟悉MATLAB用户界面
   + 导入数据到MATLAB
     - 数据导入插件
     - 数据导入命令
       - 从文件中导入变量
       - 读取 ASCII 分隔的文件
       - 读取逗号分隔的文件
       - 读取Excel
       - 读取数值、文字类型混合的文件
   + 从MATLAB导出数据
   + 处理多媒体数据
     - 处理图像
     - 音频导入、导出
   + 组织数据
     - cell array （元胞数组）
     - structure array （结构数组）
     - table （表）
     - categorical array （类型数组）
   + 总结
4. 第三章：发现数据中的模式（有用信息）
   - 区分变量的数据类型
     - 定量型变量
     - 定性型变量
   - 数据预处理
     - 观察原始数据
     - 查找缺失数据
     - 改变数据类型
     - 替换缺失数据
     - 删除缺失数据
     - 对table进行排序
     - 查找数据集中的奇异值
     - 整合多个数据源
   - 观察数据集统计特征
     - 位置指标
       - 平均值、中位数、众数
       - 分位数、百分位数
     - 弥散度指标
     - 形状指标
       - 偏度
       - 峰度
   - 数据可视化
     - 数据集统计指标对话框
     - 柱状图
     - 箱状图
     - 散点图
   - 总结
5. 第四章：回归分析——挖掘变量间关系
   - 发现线性关系
     - 最小二乘回归
     - 基础拟合用户界面
   - 如何构建线性回归模型
     - 使用更有鲁棒性的模型进行拟合
     - 多线性回归方程
       - 多线性回归方程与类别预测
   - 多项式回归
   - 回归APP
   - 总结
6. 第五章：分类分析——挖掘隐藏模式
   - 决策树分类
   - 概率视角——朴素贝叶斯分类器
     - 概率论基础
     - 使用朴素贝叶斯分类器
     - MATLAB中的贝叶斯方法
   - 频率视角——判别分析
   - 无监督学习——最邻近算法
   - 分类APP
   - 总结
7. 第六章：无监督学习——聚类分析
   - 聚类分析简介
     - 相似度与离散度指标
     - 聚类方法类型简介
       - 层次聚类
       - 原型聚类
   - 层次聚类算法
     - 层次聚类中的相似度指标
     - 定义层次聚类中的簇
     - 如何理解层次聚类图
     - 验证聚类结果
   - K-means聚类——基于均值聚类
     - K-means算法
     - keans()函数
     - silhouette图——可视化聚类结果
   - K-medoids聚类——基于样本中心聚类
     - medoids定义
     - kmedoids函数
     - 执行聚类
   - 高斯混合模型(GMM)聚类
     - 高斯分布
     - MATLAB中的GMM支持
     - 使用后验概率分布进行聚类
   - 总结
8. 第七章：人工神经网络——模拟人脑思考方式
   - 神经网络简介
   - 神经网络基础构成
     - 隐藏层数量
     - 每层中的节点数量
     - 神经网络训练方法
   - 神经网络工具箱
   - 工具箱的用户界面（GUI）
   - 使用神经网络进行拟合
     - 如何使用 Neural Fitting APP (nftool)
     - 脚本分析
   - 总结
9. 第八章：降维——改进机器学习模型性能
   - 特征选择
     - 分步回归
     - MATLAB中的分步回归支持
   - 特征提取
     - 主成分分析(PCA)
   - 总结
10. 第九章：机器学习实战
    - 预测混凝土质量
    - 使用神经网络诊断甲状腺疾病
    - 使用模糊聚类对学生进行分簇
    - 总结
11. Index




** 前言
人类是能够从经验中学习的，为什么计算机、程序不行呢？机器学习算法
(Machine Learning)正赋予了计算机、程序从经验中学习的能力。机器学
习算法通过学习原始数据，从原始数据集中提取规律、发现模式，然后用
这些规律、模式对新的数据进行预测。而这些学习到的规律、模式是算法
自主发现、无需事先编程的。因此，机器学习算法能够真正的对数据集进
行自主学习！

MATLAB对机器学习算法有非常强大的支持。同时，MATLAB还提供了丰富的
交互式图形界面帮助用户对数据、模型、计算结果进行可视化操作。使用
MATLAB机器学习工具箱进行模型建立、算法求解是件非常容易的事。

本书的写作风格是，在陈述每个主题前，先会对这个主题的理论基础进行
精炼的概述，然后会用实际案例举例，现实生活中如何应用这些机器学习
理论。通过通读本书，读者能够使用机器学习算法和全部MATLAB强大的工
具箱支持来应对现实生活中的挑战。

*** 内容提要

第一章：MATLAB机器学习初步。本章先对机器学习的基础概念
进行概述，然后快速浏览几种不同类型的机器学习算法。除此之外，还会
介绍一些MATLAB的背景、基础概念和编程环境(environment)。最后，我们
还会精选几个MATLAB提供的非常强大的机器学习工具箱进行简要介绍。

第二章：MATLAB中的数据处理。本章主要介绍MATLAB数据的导入、导出操
作。首先我们介绍了如何将数据集导入MATLAB。接着我们介绍了MATLAB用
于处理数据的几种格式。然后我们介绍了如何将数据导出MATLAB。最后我
们简洁了如何挑选合适的数据格式应对不同数据分析需求。

第三章：发现数据中的模式。本章我们开始学习如何从原始数据集中提取
有用信息。首先我们简介了几种MATLAB的变量类型。接着介绍如何对数据
集进行清理（补全、删除缺失数据等），并分情况讨论了不同情境下的最
佳方案。本章以数据可视化结尾，数据可视化是数据分析领域非常关键的
技能，请读者多学习、总结这方面的技巧。

第四章：回归分析。本章介绍了MATLAB用于回归分析的工具箱。我们从工
具箱的用户界面开始学习，继而深入到如何使用内置函数进行回归分析，
包括拟合、预测和结果可视化。

第五章：分类分析。之前的章节一直在介绍频率视角下的监督学习，从本
章开始添加了概率论、贝叶斯视角下的机器学习算法，以及非监督学习的
内容。除了基于决策树的频率视角下的分类器，你还将学习到如何使用最
近邻算法进行无监督分类，以及基于贝叶斯理论的后验概率分类器。

第六章：无监督学习。本章着重介绍无监督学习和聚类分析。在这一章中
你将学习如何把数据集归类到群、如何对相似的事物分簇。我们首先讲解
了基于层级的聚类算法，接着将扩展到基于原型(prototype-based
clustering)的聚类方法，如k-means和k-medoids算法。

第七章：人工神经网络。本章讲述了如何使用人工神经网络对数据进行拟
合、分类以及聚类。你讲学习一系列帮助提高训练效率、评估网络性能的
预处理方法、参数调优方法及网络结构可视化方法。

第八章：降维。本章讲述如何构建最能够表示数据集的特征矩阵。你将学
习对数据集的降维变换的方法，以及对数据集进行特征提取的方法。

第九章：机器学习实战。本章着重于讲述机器学习方法在实际生活中的应
用。首先你会完成一个真实的拟合任务。接着你将学习如何使用神经网络
进行分类。最后以一个聚类任务结尾。通过本章你将学习如何在实际应用
中分析、使用监督学习和非监督学习算法。

*** MATLAB环境要求
为了能运行本书中的MATLAB机器学习代码，你需要安装MATLAB（推荐使用
最新版本，写作本书时使用了R2017a），以及如下工具箱：statistics
and machine learning toolbox, neural network toolbox, and fuzzy
logic toolbox。

*** 适用读者
本书的目标人群包括数据分析员、数据科学家、学生或任何希望学习机器
学习算法以及搭建数据处理、预测应用的人群。良好的数学和统计学（大
学工科水平）背景非常有助于本书的学习。

*** 本部分以下小节没有翻译：
**** 写作规范、符号约定
**** 读者反馈
**** 顾客支持
**** 源码下载
**** 勘误
**** 版权
**** 问题

